version: '3.8'

services:
  sentimenti-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentimenti-api-prod
    ports:
      - "8002:8002"
    restart: always
    runtime: nvidia  
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
