name: vm-base
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - numpy
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - cuda-cudart=11.8
  - cuda-runtime=11.8
  - mkl
  - mkl-service
  - mkl-include
  - pip:
      - transformers==4.49.0
      - tokenizers==0.21.0
      - huggingface-hub==0.29.1
      - python-multipart
      - annotated-types==0.7.0
      - pydantic==2.10.6
      - pydantic_core==2.27.2

